### ISSUE TITLE
Firefox Desktop

### ISSUE THREAD

**Issue by emfeather94** [char1129/web-design-2-independent-project#11]
- Your site is looking good Sarah! I like where you are going with it. Original name too!
- all your links seem to be working great
- As you continue working, just make sure youre giving everything enough breathing room, around pictures, buttons and between sections. I would also suggest giving some margins on either side of the page to push everything in a bit more and shorten up that line length
- Overall its looking great, keep it up!

**Comment by char1129** [comment]
Thank you Emily!!
