### ISSUE TITLE
Prase Error

### ISSUE THREAD

**Issue by char1129** [char1129/web-design-2-independent-project#15]
@jessJodoin

Hi Jess, 
I am cleaning up my code to ready it for submission and I have this parse error that is moving around the main.css file.
I remove the part of the code it says its in, and it just moves a line up. Could you help me locate what it wants me to fix?
<img width="440" alt="Screen Shot 2020-12-17 at 12 42 17 PM" src="https://user-images.githubusercontent.com/55107755/102523324-6082ee00-4065-11eb-837d-cdbd9e6e5f7b.png">

Help please 😊 Thank you!

**Comment by JessJodoin** [comment]
Oh your last media query is missing a closing } at the end and then everything inside it needs to be tabbed in once 😄

**Comment by char1129** [comment]
@JessJodoin Sorry I noticed that after I pushed it. That was my troubleshooting, I've replaced it and I pushed it again. 
I still have an error at 969. I've indented everything to clean up the search.

**Comment by JessJodoin** [comment]
Oh your 25em media query is also missing a closing }

**Comment by char1129** [comment]
OMG thank you! I was looking for that missing brace everywhere!!!! Thank you!
