### ISSUE TITLE
Markbot Error Msg

### ISSUE THREAD

**Issue by char1129** [char1129/web-design-2-independent-project#2]
<img width="487" alt="Screen Shot 2020-12-04 at 1 53 12 PM" src="https://user-images.githubusercontent.com/55107755/101203004-0da64100-3638-11eb-869d-8d1073b185e0.png">

I'm not quite sure what markbot is upset about here? I put a space after the : and it didn't work.
@jessJodoin
@hellaChella

**Comment by JessJodoin** [comment]
Which css file are those issues for?

**Comment by char1129** [comment]
Main.css @JessJodoin Thank you!

**Comment by JessJodoin** [comment]
For whatever reason when I throw it into Markbot I get those errors for different lines

<img width="588" alt="Screen Shot 2020-12-04 at 2 19 19 PM" src="https://user-images.githubusercontent.com/43217543/101205501-b609d480-363b-11eb-8692-d980d6ccdd03.png">

I'm assuming everything is committed?

**Comment by char1129** [comment]
Yes I updated my commits 20 mins ago.

**Comment by JessJodoin** [comment]
For line 48: just put it all on one line cause for whatever reason Markbot doesn't like it on multiple lines (what a baby lol)
`grid-template-areas: "hero-banner hero-banner hero-banner";`

Line 107: there's a space missing between : and rgba
`background: rgba(255, 255, 255, .5);`

Line 277, 292, and 358: there are two spaces between the : and 1 just remove one
`grid-row: 1;`

Hopefully that fixes those errors 😄 Let me know if there's anything else I can help with 👍

**Comment by char1129** [comment]
Oh my lord. I just noticed this and was coming back to close the comment. Sorry about that! Thank you Jess!!!!
