### ISSUE TITLE
Very nice!

### ISSUE THREAD

**Issue by laura-hopk** [char1129/web-design-2-independent-project#3]
Your website looks really nice! Very modern and sophisticated.
A few things I noticed that need some tweaking! Firstly the alt tags on your images! An easy fix, just add something like "alt="placeholder image" ". 
Also your images need to have placeholders! Again, very easy to fix, just add a background colour to your images in the css. 

Great work! Looks fantastic so far!

**Comment by char1129** [comment]
> Your website looks really nice! Very modern and sophisticated.
> A few things I noticed that need some tweaking! Firstly the alt tags on your images! An easy fix, just add something like "alt="placeholder image" ".
> Also your images need to have placeholders! Again, very easy to fix, just add a background colour to your images in the css.
> 
> Great work! Looks fantastic so far!

Thank you Laura! Will do!
