### ISSUE TITLE
Opera PC

### ISSUE THREAD

**Issue by jessicali673** [char1129/web-design-2-independent-project#5]
Your layout for your website so far is looking very promising! Cool designs.
I love your slogan and your site is responsive.
For opera on Pc, I would just watch out for line length, simple fix with margins!
![image](https://user-images.githubusercontent.com/55094160/101939825-89156e80-3bb3-11eb-9e74-f4923d3e1cbe.png)
I'm sure you're still working on it but showing you how the resume looks so far on Opera - it's a little confusing

Great Job!

**Comment by char1129** [comment]
Thanks @jessicali673 !! I'll keep all tips in mind! :) Good luck with the rest of the semester!
