### ISSUE TITLE
Web Performance

### ISSUE THREAD

**Issue by lilbaj** [char1129/web-design-2-independent-project#8]
<img width="1020" alt="Screen Shot 2020-12-11 at 2 01 54 PM" src="https://user-images.githubusercontent.com/55108804/101943727-9fbec400-3bb9-11eb-8c4c-aa053b706c77.png">
<img width="1020" alt="Screen Shot 2020-12-11 at 2 02 00 PM" src="https://user-images.githubusercontent.com/55108804/101943734-a2211e00-3bb9-11eb-9b34-cf88790cd13e.png">

Hey Sarah,

Don't freak tbh this is a very common score that I've been seeing. Not exactly sure how to fix the cashe but honestly i think its fine. great work!!

**Comment by char1129** [comment]
@lilbaj Nice :) Thank you Lila!!
